version: "3.3"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#

services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  tests_db:
    restart: always
    image: postgres
    volumes:
      - ./tests_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=tests
      - POSTGRES_PASSWORD=tests
    ports:
      - "37650:5432"
