"""init

Revision ID: 0975d1978e8f
Revises: 
Create Date: 2021-10-18 22:14:06.675281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0975d1978e8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('desc', sa.String(length=116), nullable=False),
    sa.Column('categories', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.String(length=50000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_categories'), 'content', ['categories'], unique=False)
    op.create_index(op.f('ix_content_desc'), 'content', ['desc'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=254), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_desc'), table_name='content')
    op.drop_index(op.f('ix_content_categories'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
