"""desc limit

Revision ID: 82882eba86c5
Revises: ba07ecccba42
Create Date: 2021-10-25 02:58:24.512234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82882eba86c5'
down_revision = 'ba07ecccba42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'desc',
               existing_type=sa.VARCHAR(length=116),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'desc',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=116),
               existing_nullable=False)
    # ### end Alembic commands ###
