"""empty message

Revision ID: e90f87355675
Revises: ccdd01c9a0c6
Create Date: 2021-10-18 01:39:43.468217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90f87355675'
down_revision = 'ccdd01c9a0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('categories', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.String(length=50000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_categories'), 'content', ['categories'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_categories'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
